// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// update_p_vl_cpp
NumericMatrix update_p_vl_cpp(NumericMatrix prob_y0_v, NumericMatrix B0, NumericMatrix p_vl_curr, NumericMatrix p_vl_R1, int max_iter, double tol);
RcppExport SEXP _joint2phase_update_p_vl_cpp(SEXP prob_y0_vSEXP, SEXP B0SEXP, SEXP p_vl_currSEXP, SEXP p_vl_R1SEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type prob_y0_v(prob_y0_vSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p_vl_curr(p_vl_currSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type p_vl_R1(p_vl_R1SEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(update_p_vl_cpp(prob_y0_v, B0, p_vl_curr, p_vl_R1, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_joint2phase_update_p_vl_cpp", (DL_FUNC) &_joint2phase_update_p_vl_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_joint2phase(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
