# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_p_vl_cpp <- function(prob_y0_v, B0, p_vl_curr, p_vl_R1, max_iter, tol) {
    .Call(`_joint2phase_update_p_vl_cpp`, prob_y0_v, B0, p_vl_curr, p_vl_R1, max_iter, tol)
}

